#!/bin/sh
### BEGIN INIT INFO
# Provides:          guacamole
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Guacamole server
# Description:       Start the web server
#  This script will start the guacamole server.
### END INIT INFO

DESC="Guacamole server"

case "$1" in
  start)
        echo "Starting $DESC"
        /usr/local/sbin/guacd
        ;;
  stop)
        echo "Stopping $DESC"
        killall guacd
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

exit 0
